### ISSUE TITLE
spAmeEr doEsnT woRk

### ISSUE THREAD

**Issue by PlavnikHacks** [MysteryBlokHed/Yolosmith#2]
cant even code a correct spammer "they added recaptcha now i cant use it 😢 😢 😢 😢 "

bro cant even make a bypass
shitty python developers LOLOL

**Comment by PlavnikHacks** [comment]
https://www.youtube.com/watch?v=_cFIPMDhytY

**Comment by MysteryBlokHed** [comment]
Thank you for your input! The original Python spammer mimicked the requests that YOLO usually sent as opposed to opening a browser window and entering text/clicking buttons. This made it significantly faster than any program that would do something like controlling Chrome and visting the website. When reCAPTCHA was added, it meant that I would have had to fake reCAPTCHA results, something that Google is well aware of people trying to do. This would make it very difficult to do something like that. I have spent very little time trying to see if YOLO made a mistake in their implementation of reCAPTCHA, so I don't know if there's any way around it that would allow a program similar to the original spammer.

I hope this clears up any confusion 👍

**Comment by PlavnikHacks** [comment]
Yolo is shut down either way so this wont work ever #shitdev kys

**Comment by MysteryBlokHed** [comment]
Hence why the last commit was in April.

**Comment by supercam19** [comment]
> cant even code a correct spammer "they added recaptcha now i cant use it 😢 😢 😢 😢 "
> 
> bro cant even make a bypass
> shitty python developers LOLOL

Shut the fuck up dumbass
👊😩
👋😳

**Comment by LumpcasElBurrito** [comment]
👊😩
👋😳
Indeed 
More like joe burger gone sus in among us but with side of crewmate fries and extra sussy slurpie like imposter give me sloppy like a dododododo gone susxual #amongus #sus #dododo do do fortnite balls.
